# Use postgres/example user/password credentials
# version: '3.1'

# services:

#   db:
#     image: postgres:14.5-alpine
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080


version: "3"
services:
  database:
    image: postgres:14.5-alpine
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=api_rest_typescript"
    ports:
      - 5441:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      # - pg-config:/etc/postgresql
    # entrypoint: docker-entrypoint.sh -c 'config_file=/etc/postgresql/postgresql.conf'
volumes:
  pg-data:
  # pg-config:
  #   driver: local
  #   driver_opts:
  #     type: "none"
  #     o: "bind"
  #     device: "$PWD/postgres_custom"